AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create a single-node ElastiCache for Valkey cluster.
  This template IMPORTS network resources and EXPORTS its own resources.

# Phần Parameters đã được xóa bỏ để dùng ImportValue

Resources:
  # Resource 0: Tạo Security Group cho EC2 app host để cho phép truy cập vào ElastiCache
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow traffic from App SG to ElastiCache on Valkey port 6379"
      VpcId: !ImportValue Project01-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !ImportValue Project01-EC2-SG-ID

  # Resource 1: Tạo Security Group riêng cho ElastiCache, cho phép truy cập từ AppSecurityGroup
  CacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow traffic from App SG to ElastiCache on Valkey port 6379"
      VpcId: !ImportValue Project01-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref AppSecurityGroup

  # Resource 2: Tạo Subnet Group cho ElastiCache
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet group for the e-commerce cache, using private subnets."
      SubnetIds:
        - !ImportValue Project01-Private-Subnet-1a
        - !ImportValue Project01-Private-Subnet-1b

  # Resource 3: Tạo cụm ElastiCache Replication Group
  ElastiCacheCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: "Valkey cache for e-commerce application"
      Engine: valkey
      EngineVersion: "8.0"
      CacheNodeType: "cache.t3.micro"
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      SecurityGroupIds:
        - !GetAtt CacheSecurityGroup.GroupId
      NumNodeGroups: 1
      ReplicasPerNodeGroup: 0
      AutomaticFailoverEnabled: false
      MultiAZEnabled: false
      CacheParameterGroupName: "default.valkey8"
      TransitEncryptionEnabled: false

Outputs:
  CacheEndpointAddress:
    Description: "The Primary Endpoint of the ElastiCache Valkey cluster"
    Value: !GetAtt ElastiCacheCluster.PrimaryEndPoint.Address
    Export:
      Name: Prj01-Cache-EndpointAddress

  CacheEndpointPort:
    Description: "The Port of the ElastiCache Valkey cluster"
    Value: !GetAtt ElastiCacheCluster.PrimaryEndPoint.Port
    Export:
      Name: Prj01-Cache-EndpointPort

  AppSecurityGroupId:
    Description: "The Security Group ID of the App Security Group"
    Value: !GetAtt AppSecurityGroup.GroupId
    Export:
      Name: Prj01-EC2-to-Cache-SG-ID

  CacheSecurityGroupId:
    Description: "The Security Group ID of the ElastiCache cluster"
    Value: !GetAtt CacheSecurityGroup.GroupId
    Export:
      Name: Prj01-Cache-SecurityGroupId
