AWSTemplateFormatVersion: "2010-09-09"
Description: RDS PostgreSQL Multi-AZ

Resources:
  # Subnet group for Aurora
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL
      SubnetIds:
        - !ImportValue Project01-Private-Subnet-1a
        - !ImportValue Project01-Private-Subnet-1b
      Tags:
        - Key: Name
          Value: Project01-DB-Subnet-Group

  # Secrets Manager for DB
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Project01-DB-Secret
      Description: Credentials for RDS PostgreSQL and Proxy
      SecretString: !Sub |
        {
          "username": "prj01",
          "password": "From1to10"
        }
      Tags:
        - Key: Name
          Value: Project01-DB-Secret

  # Aurora DB Cluster with 1 instance and 1 read replica
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: project01-aurora-cluster
      Engine: aurora-postgresql
      MasterUsername:
        !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:username}}"
      MasterUserPassword:
        !Sub "{{resolve:secretsmanager:${DBSecret}:SecretString:password}}"
      DatabaseName: coffee
      DBSubnetGroupName: !Ref DBSubnetGroup
      Port: 5432
      VpcSecurityGroupIds:
        - !ImportValue Project01-DBtoEC2-DB-SG-ID
      BackupRetentionPeriod: 7
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: Project01-Aurora-Cluster

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: Project01-DB-Instance
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-postgresql
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: Project01-Aurora-Instance
  
  AuroraReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: Project01-DB-Replica
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-postgresql
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: Project01-DB-Replica

Outputs:
  DBSecretArn:
    Description: ARN of the DB secret
    Value: !Ref DBSecret
    Export:
      Name: Project01-DB-Secret-Arn
  DBSubnetGroupName:
    Description: Name of the DB subnet group
    Value: !Ref DBSubnetGroup
    Export:
      Name: Project01-DB-Subnet-Group-Name
  AuroraClusterId:
    Description: ID of the Aurora cluster
    Value: !Ref AuroraCluster
    Export:
      Name: Project01-Aurora-Cluster-Id
  AuroraClusterEndpoint:
    Description: Endpoint of the Aurora cluster
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: Project01-Aurora-Cluster-Endpoint
  AuroraReplicaId:
    Description: ID of the Aurora read replica
    Value: !Ref AuroraReplica
    Export:
      Name: Project01-Aurora-Replica-Id
  AuroraReplicaEndpoint:
    Description: Endpoint of the Aurora read replica
    Value: !GetAtt AuroraReplica.Endpoint.Address
    Export:
      Name: Project01-Aurora-Replica-Endpoint
